name: build

on:
  push:
    branches:
    - master

jobs:
  hello_world_docker:
    runs-on: ubuntu-latest
    name: A docker job to say hello
    steps:
      - uses: actions/checkout@v1
      - name: Hello world Docker action step
        id: docker
        uses: ./actions/docker/hello-world
        with:
          who-to-greet: 'Mr Docker'
      - name: Get the output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
  
  hello_world_js:
    runs-on: ubuntu-latest
    name: A JavaScript job to say hello
    steps:
      - uses: actions/checkout@v1
      - name: Hello world JavaScript action step
        id: js
        uses: ./actions/js/hello-world
        with:
          whoToGreet: 'Mr JavaScript'
