name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  node:10.16-jessie

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
  
    - run: npm ci

    - run: node client.js
      working-directory: ./redis
      env:
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}

    - name: Build application
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Unit tests
      run: yarn test
