name: build

on:
  push:
    branches:
    - master

jobs:
  hello-world-docker:
    runs-on: ubuntu-latest
    name: A docker job to say hello
    steps:
      - uses: actions/checkout@v1
      - name: Hello world step
        id: hello
        uses: ./actions/docker/hello-world
        with:
          who-to-greet: Paul
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  
  hello-world-js:
    runs-on: ubuntu-latest
    name: A JavaScript job to say hi
    steps:
      - uses: actions/checkout@v1
      - name: Hi step
        uses: ./actions/js/hello-world
        with:
          who-to-greet: Paul
