name: envvars

on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Env vars
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          AGE: 21
        run: echo "$AGE"
