name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Environment variables test
      env:
        FIRST_NAME: ${{ secrets.FIRST_NAME }}
        LAST_NAME: ${{ secrets.LAST_NAME }}
      run: |
        echo $FIRST_NAME $LAST_NAME
    - name: yarn install, build, and test
      run: |
        yarn
        yarn build --if-present
        yarn test
      env:
        CI: true
